export const pagesInfo = [
  {
    id: 0,
    freshProduceImg: "https://media.istockphoto.com/id/1208790364/photo/healthy-fresh-rainbow-colored-fruits-and-vegetables-in-a-row.jpg?b=1&s=170667a&w=0&k=20&c=wUmdSBiDut4iwEoccdNTr6Iqt8h31kU8Kh106WeDrbk=",
    categoryName: "FreshProduce",
    categoryNamed: "Fruits . Vegetables",
    type1: "Vegetables",
    type2: "Fruits",
    disc: 'No more running to local shops in heat and dust as Smart Foods gives you the convenience of ordering wide range of fresh, temperature controlled vegetables from your home.'
  },
  {
    id: 1,
    freshProduceImg: "https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,h_1200,q_75,w_1200/v1/clients/frederickcountymd/Debs_Artisan_Bakehouse_7497148e-46e2-4562-bb0f-8fcfc6fba3a1.jpg",
    categoryName: "BakeryGoods",
    categoryNamed: "Breads . Deserts",
    type1: "Breads",
    type2: "Deserts",
    disc: 'We provide you with soft and fresh baked breads, cakes, biscuits and many more. We believe in customer preference and their needs.'
  },
  {
    id: 2,
    freshProduceImg: "https://media.istockphoto.com/id/1283712032/photo/cardboard-box-filled-with-non-perishable-foods-on-wooden-table-high-angle-view.jpg?s=612x612&w=0&k=20&c=7B2cUwQB2LeBmIh5JElkO5DoE7GRq-CRVmERsMSJoVY=",
    categoryName: "PantryStaples",
    categoryNamed: "Essentials . Lentils",
    type1: "Essentials",
    type2: "Lentils",
    disc: 'Tired of running to superstores for flour, rice, oil, jam etc? We provide you these items with the best deals you can afford and deliver to your homes in no time.'

  },
]
export const vegetablesInfo = [
  {
    id: 0,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://post.healthline.com/wp-content/uploads/2020/09/AN440-Potatoes-732x549-thumb-732x549.jpg",
    price: 40,
    prices: "40/kg",
    priceTag: "kg",
    head: "Potato",
    disc: "Potatoes are a fresh produced food in many cuisines around the world.",
    quantity: 1,
  },
  {
    id: 1,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://www.wondriumdaily.com/wp-content/uploads/2020/03/header-16.jpg",
    head: "Tomato",
    disc: "Tomato is widely used in cooking for its vibrant color and distinct flavor.",
    price: 60,
    prices: "60/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 2,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://i0.wp.com/images-prod.healthline.com/hlcmsresource/images/AN_images/onions-benefits-1296x728-feature.jpg?w=1155&h=1528",
    head: "Onion",
    disc: "Onion is a vegetable widely used in cooking for its distinctive flavor and aroma.",
    price: 50,
    prices: "50/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 3,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://post.healthline.com/wp-content/uploads/2020/09/AN88-Cucumbers-732x549-thumb-1-732x549.jpg",
    head: "Cucumber",
    disc: "Cucumbers are typically eaten fresh and can be enjoyed in different ways.",
    price: 20,
    prices: "20/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 4,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://bakeitwithlove.com/wp-content/uploads/2022/06/Diced-Green-Chiles-Substitute-sq.jpg",
    head: "Green Chili",
    disc: "Green chilies are widely used in various cuisines around the world",
    price: 240,
    prices: "240/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 5,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lemons.jpg?itok=W6bdcxfq",
    head: "Lemons",
    disc: "Lemon is a citrus fruit known for its sour taste and acidic juice.",
    price: 120,
    prices: "120/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 6,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://www.thespruceeats.com/thmb/KREtRDgPBBevtf_YaN3oavhGQFU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/what-are-bell-peppers-5216131-still-life-9960d1febfd64dde9de5134dc184529e.jpg",
    head: "Bell Pepper",
    disc: "Bell Pepper is popular for its mild and sweet flavor.",
    price: 80,
    prices: "80/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 7,
    categoryName: "FreshProduce",
    tag: "v",
    image:
      "https://cdn-prod.medicalnewstoday.com/content/images/articles/277/277627/bunch-of-fresh-coriander-or-cilantro-on-a-wooden-table.jpg",
    head: "Coriander",
    disc: "Coriander leaves have a fresh, citrusy, and slightly peppery taste.",
    price: 200,
    prices: "200/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 8,
    categoryName: "BakeryGoods",
    tag: "b",
    image:
      "https://ikneadtoeat.com/wp-content/uploads/2021/11/chicken_bread_featured_image-1.jpg",
    head: 'Chicken Bread 6" ',
    disc: "Chicken Bread is a popular baked dish that combines the flavors of chicken and bread.",
    price: 200,
    prices: "200/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 9,
    categoryName: "BakeryGoods",
    tag: "b",
    image:
      "https://misskabaki.co.ke/wp-content/uploads/2021/11/Vegetarian-Samosas-47-scaled.jpg",
    head: "Baked Samosa",
    disc: "Baked samosas are a healthier alternative to traditional deep-fried samosas.",
    price: 50,
    prices: "50/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 10,
    categoryName: "BakeryGoods",
    tag: "b",
    image:
      "https://www.nehascookbook.com/wp-content/uploads/2022/09/Spring-roll-WS-1.jpg",
    head: "Spring Roll",
    disc: "Spring rolls are a popular Asian appetizer or snack made with a crispy wrapper",
    price: 60,
    prices: "60/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 11,
    categoryName: "BakeryGoods",
    tag: "b",
    image:
      "https://www.mirchitales.com/wp-content/uploads/2015/10/DesiChickenPatties-14.jpg",
    head: "Chicken Patties",
    disc: "Chicken patties are flavorful and versatile appetizers made with ground chicken.",
    price: 80,
    prices: "80/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 12,
    categoryName: "BakeryGoods",
    tag: "b",
    image:
      "https://static.toiimg.com/thumb/53110049.cms?width=1200&height=900",
    head: 'Pizza regular 10"',
    disc: "Pizza is a popular Italian dish loved by people all around the world",
    price: 850,
    prices: "850/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 13,
    categoryName: "BakeryGoods",
    tag: "b",
    image:
      "https://hips.hearstapps.com/hmg-prod/images/baked-ziti-1671215342.jpeg?crop=0.948xw:0.474xh;0.0179xw,0.257xh&resize=1200:*",
    head: "Baked Pasta",
    disc: "Baked pasta is a delicious and comforting dish.",
    price: 600,
    prices: "600/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 14,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://www.goodness.com.au/product_images/uploaded_images/guide-to-flours-types-and-uses-spelt.jpg",
    price: 80,
    prices: "80/kg",
    priceTag: "kg",
    head: "Flour",
    disc: "Flour is a versatile ingredient used in cooking and baking.",
    quantity: 1,
  },
  {
    id: 15,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://www.thespruceeats.com/thmb/kUoSjpktuKuTQpxkm-OFgOxl8s4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-make-basic-white-rice-2355883-10-5b0da96eba6177003622896e.jpg",
    head: "Rice",
    disc: "Rice is a staple food and a dietary staple for a large portion of the world's population.",
    price: 320,
    prices: "320/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 16,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://cdn.britannica.com/94/151894-050-F72A5317/Brown-eggs.jpg",
    head: "Eggs",
    disc: "Eggs are a versatile and widely used ingredient in cooking and baking.",
    price: 30,
    prices: "30/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 17,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://sundayguardianlive.com/wp-content/uploads/2022/09/natural-honey-500x500.jpg",
    head: "Honey",
    disc: "Honey is versatile natural sweetener with a rich history and cultural significance",
    price: 1200,
    prices: "1200/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 18,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://assets.bonappetit.com/photos/5cc1f251f8ab2775109895c7/16:9/w_1280,c_limit/Basically-Vinegar-Group-Update.jpg",
    head: "Vinegar",
    disc: "Vinegar is a versatile ingredient that adds acidity and tanginess to a variety of dishes.",
    price: 240,
    prices: "240/ltr",
    priceTag: "ltr",
    quantity: 1,
  },
  {
    id: 19,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://hips.hearstapps.com/hmg-prod/images/gettyimages-1206682746.jpg",
    head: "Cooking Oil",
    disc: "Cooking oil is used in various cooking methods to enhance flavors.",
    price: 650,
    prices: "650/ltr",
    priceTag: "ltr",
    quantity: 1,
  },
  {
    id: 20,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://images.everydayhealth.com/images/salt-101-guide-why-you-need-it-how-much-is-too-much-how-to-cut-back-alt-1440x810.jpg",
    head: "Salt",
    disc: "Salt is a mineral compound composed mainly of sodium chloride (NaCl).",
    price: 40,
    prices: "40/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 21,
    categoryName: "PantryStaples",
    tag: "v",
    image:
      "https://post.healthline.com/wp-content/uploads/2020/08/black-pepper-benefits-732x549-thumbnail.jpg",
    head: "Black Pepper",
    disc: "Black pepper is a popular spice derived from the dried berries of the pepper plant.",
    price: 1600,
    prices: "1600/kg",
    priceTag: "kg",
    quantity: 1,
  },
];
export const fruitsInfo = [
  {
    id: 0,
    categoryName: "FreshProduce",
    tag: "f",
    image: "https://i.hurimg.com/i/hdn/75/0x0/6326faa64e3fe1167045aee9.jpg",
    head: "Mango",
    disc: "Mango is a tropical fruit that is known for its sweet and juicy taste.",
    price: 160,
    prices: "160/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 1,
    categoryName: "FreshProduce",
    tag: "f",
    image:
      "https://i0.wp.com/post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/07/what_to_know_apples_green_red_1296x728_header-1024x575.jpg?w=1155&h=1528",
    head: "Apple",
    disc: "Apple is a popular fruit known for its crisp texture and sweet or tart flavor",
    price: 300,
    prices: "300/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 2,
    categoryName: "FreshProduce",
    tag: "f",
    image:
      "https://www.eatthis.com/wp-content/uploads/sites/4/2021/07/bananas.jpg?quality=82&strip=all",
    head: "Banana",
    disc: "Bananas are also versatile and can be used in various culinary preparations.",
    price: 150,
    prices: "150/Dozen",
    priceTag: "Dozen",
    quantity: 1,
  },
  {
    id: 3,
    categoryName: "FreshProduce",
    tag: "f",
    image:
      "https://clv.h-cdn.co/assets/15/22/2048x2048/square-1432664914-strawberry-facts1.jpg",
    head: "Strawberry",
    disc: "Strawberry is a delicious and vibrant fruit known for its sweet and tangy flavor.",
    price: 280,
    prices: "280/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 4,
    categoryName: "FreshProduce",
    tag: "f",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg",
    head: "PineApple",
    disc: "Pineapple is a tropical fruit known for its tangy flavor and distinctively spiky exterior.",
    price: 600,
    prices: "600/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 5,
    categoryName: "FreshProduce",
    tag: "f",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/43/Ambersweet_oranges.jpg",
    head: "Orange",
    disc: "Oranges are citrus fruits known for their refreshing flavor, and high vitamin C content. ",
    price: 520,
    prices: "520/Dozen",
    priceTag: "Dozen",
    quantity: 1,
  },
  {
    id: 6,
    categoryName: "BakeryGoods",
    tag: "d",
    image: "https://hips.hearstapps.com/hmg-prod/images/man-dispensing-cakes-in-a-pastry-bakery-royalty-free-image-1676319170.jpg?crop=1.00xw:0.752xh;0,0.106xh&resize=1200:*",
    head: "Pastries",
    disc: "Pastries are a delicious category of baked goods.",
    price: 120,
    prices: "120/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 7,
    categoryName: "BakeryGoods",
    tag: "d",
    image:
      "https://www.allrecipes.com/thmb/8xwaWAHtl_QLij6D-G0Z4B1HDVA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/10813-best-chocolate-chip-cookies-mfs-146-4x3-b108aceffa6043a1ac81c3c5a9b034c8.jpg",
    head: "Cookies",
    disc: "Cookies are delightful baked treats that come in various shapes, flavors, and textures.",
    price: 800,
    prices: "800/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 8,
    categoryName: "BakeryGoods",
    tag: "d",
    image:
      "https://images.immediate.co.uk/production/volatile/sites/30/2021/03/Unicorn-cake-32e0971.jpg",
    head: "Cakes",
    disc: "Cakes are delightful desserts that are perfect for celebrating special occasions",
    price: 900,
    prices: "900/Pound",
    priceTag: "Pound",
    quantity: 1,
  },
  {
    id: 9,
    categoryName: "BakeryGoods",
    tag: "d",
    image:
      "https://cdn.britannica.com/38/230838-050-D0173E79/doughnuts-donuts.jpg",
    head: "Donuts",
    disc: "Donuts are delicious baked pastries that are typically round with a hole in the center.",
    price: 80,
    prices: "80/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 10,
    categoryName: "BakeryGoods",
    tag: "d",
    image:
      "https://static.onecms.io/wp-content/uploads/sites/43/2022/05/19/228553-MoistChocolateMuffins-mfs-2X3-0923.jpg",
    head: "Muffin",
    disc: "Muffins are versatile baked treats that are often enjoyed for breakfast or as a snack.",
    price: 160,
    prices: "160/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 11,
    categoryName: "BakeryGoods",
    tag: "d",
    image:
      "https://www.eatthis.com/wp-content/uploads/sites/4/2015/12/thanksgiving-pies.jpg?quality=82&strip=1",
    head: "Pies",
    disc: "Pie is a delicious baked dish consisting of a sweet filling enclosed in a pastry crust.",
    price: 240,
    prices: "240/Pc",
    priceTag: "Pc",
    quantity: 1,
  },
  {
    id: 12,
    categoryName: "PantryStaples",
    tag: "f",
    image: "https://www.finedininglovers.com/sites/g/files/xknfdk626/files/2021-06/black-lentils%C2%A9iStock.jpg",
    head: "Black Lentil",
    disc: "Black lentils are small, dark-colored legumes that are commonly used in cooking.",
    price: 320,
    prices: "320/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 13,
    categoryName: "PantryStaples",
    tag: "f",
    image:
      "https://fdorganic.com/cdn/shop/products/FarmerDirect-Website-Products-Lentils-Organic-SplitRed-3_2x_92a3ed40-1c2d-4321-bdaa-dbd5afba2bcf_900x.jpg?v=1649708640",
    head: "Red Lentils",
    disc: "Red lentils are a type of lentil that is widely used in cooking.",
    price: 240,
    prices: "240/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 14,
    categoryName: "PantryStaples",
    tag: "f",
    image:
      "https://www.culinaryhill.com/wp-content/uploads/2023/01/How-to-Roast-Chickpeas-1200-x-800-Culinary-Hill.jpg",
    head: "ChickPeas",
    disc: "Chickpeas, also known as garbanzo beans widely used in cooking around the world. ",
    price: 320,
    prices: "320/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 15,
    categoryName: "PantryStaples",
    tag: "f",
    image:
      "https://i0.wp.com/post.medicalnewstoday.com/wp-content/uploads/sites/3/2019/11/lentils-in-a-jug-and-on-a-spoon.jpg?w=1155&h=1734",
    head: "Brown Lentil",
    disc: "Brown lentils Spanish pardina lentils, are a type of legume widely used in cooking.",
    price: 180,
    prices: "180/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 16,
    categoryName: "PantryStaples",
    tag: "f",
    image:
      "https://lifeatthetable.com/wp-content/uploads/2018/12/Black-eyed-pea-from-lowly-cowpea-to-center-stage-1080x675.jpg",
    head: "Black Eyed Beans",
    disc: "Black-eyed beans are a type of legume widely consumed around the world.",
    price: 400,
    prices: "400/kg",
    priceTag: "kg",
    quantity: 1,
  },
  {
    id: 17,
    categoryName: "PantryStaples",
    tag: "f",
    image:
      "https://cdn.apartmenttherapy.info/image/upload/v1559169776/k/archive/98bb592af3816af37362ef44e020d69df9ccac1b.jpg",
    head: "Green Lentil",
    disc: "Strawberry is a delicious and vibrant fruit known for its sweet and tangy flavor.",
    price: 260,
    prices: "260/kg",
    priceTag: "kg",
    quantity: 1,
  },
];
